### ISSUE TITLE
UTF-8 BOM in xml response causes SPIN-01004 No matching data format detected

### ISSUE THREAD

**Issue by bergner** [camunda/camunda-spin#21]
Given an xml document that starts with a UTF-8 BOM the S(response) function is unable to detect the data format as xml. Using the XML(response) also fails. I tried S(response, "application/xml") in Groovy scripting context based on Java documentation but that failed with a different error indicating that no matching function with 2 arguments could be found.

I've fixed the service in question that was returning responses with a BOM but wanted to make you aware of this. Small example and partial stack trace from Camunda below with "PROCESSING RESPONSE" being me just doing println response. The BOM unicode code point is displayed as <U+FEFF> here but the raw byte representation is \xEB\xBB\xBF (which is correct for UTF-8)

```
PROCESSING RESPONSE: <U+FEFF><?xml version="1.0" encoding="utf-8"?><atom:entry xmlns:atom="http://www.w3.org/2005/Atom"><atom:id>3a61f702-f324-4966-ad65-7b1241aa4e2a</atom:id><atom:title>test</atom:title></atom:entry>
26-Oct-2018 14:43:58.544 SEVERE [http-nio-8080-exec-10] org.camunda.commons.logging.BaseLogger.logError ENGINE-16006 BPMN Stack Trace:
        Task_0994ntm (activity-execute, ProcessInstance[8fe78383-d92d-11e8-ad80-0242c0a80004])
        Task_0994ntm
          ^
          |
        StartEvent_1
          ^
          |
        Task_1hh1sqk, name=Create file set
          ^
          |
        Task_1ecoaqb
          ^
          |
        StartEvent_1

26-Oct-2018 14:43:58.545 SEVERE [http-nio-8080-exec-10] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context: Unable to evaluate script: org.camunda.spin.spi.SpinDataFormatException: SPIN-01004 No matching data format detected
 org.camunda.bpm.engine.ScriptEvaluationException: Unable to evaluate script: org.camunda.spin.spi.SpinDataFormatException: SPIN-01004 No matching data format detected
        at org.camunda.bpm.engine.impl.scripting.CompiledExecutableScript.evaluate(CompiledExecutableScript.java:57)
        at org.camunda.bpm.engine.impl.scripting.SourceExecutableScript.evaluate(SourceExecutableScript.java:57)
        at org.camunda.bpm.engine.impl.scripting.ExecutableScript.execute(ExecutableScript.java:59)

```

**Comment by sdorokhova** [comment]
Hi @bergner ,
thank you for reporting the problem.

I create a JIRA issue for it: https://app.camunda.com/jira/browse/CAM-9461

Feel free to provide a PR 😉 

Best regards,
Svetlana
