### ISSUE TITLE
Jackson version

### ISSUE THREAD

**Issue by shannoncolavita** [camunda/camunda-spin#8]
Hi There can you update the jackson version to 2.6.3...The maven dependencies (http://mvnrepository.com/artifact/org.camunda.spin/camunda-spin-dataformat-json-jackson/1.2.0) say this is using that version put your pom is using 2.5.3

Thanks
Shannon

**Comment by ThorbenLindhauer** [comment]
Hi Shannon,

Feel free to submit a pull request.

Cheers,
Thorben

**Comment by shannoncolavita** [comment]
Cool

**Comment by shannoncolavita** [comment]
I've submitted a pull request
