### ISSUE TITLE
[CAM-12041] SPIN: De-serialization of Lists works but Collections and Maps are not implemented.

### ISSUE THREAD

**Issue by zambrovski** [camunda/camunda-spin#91]
Hi folks,

I just created a JIRA issue CAM-12041 (https://jira.camunda.com/browse/CAM-12041)
and provided a PR https://github.com/camunda/camunda-spin/pull/90 fixing it.

Please have a look on it.

Kind regards,

Simon

**Comment by yanavasileva** [comment]
The fix has been merged with 2309d30 from PR #90.
